language: go
go:
- '1.8'
sudo: true
before_install:
- sudo add-apt-repository ppa:masterminds/glide -y
- sudo apt-get update -q
- sudo apt-get install glide -y
install:
- glide install
- go get github.com/mjibson/esc
- go get github.com/ahmetb/govvv
- go get github.com/franciscocpg/gox
script:
- pwd
- ls -l
- cd ${TRAVIS_BUILD_DIR}/cmd && go generate && cd ${TRAVIS_BUILD_DIR}
- cd ${TRAVIS_BUILD_DIR}/pkg && go generate && cd ${TRAVIS_BUILD_DIR}
- CGO_ENABLED=0 gox -verbose -ldflags="$(govvv -flags)" -ldflags="-s -w" -os="linux
  darwin windows" -arch="amd64 386 armv5 armv6 armv7 arm64" -osarch="!darwin/arm64
  linux/ppc64 linux/ppc64le" -ldflags "-extldflags \"-static\"" -output="dist/rai-srcmanager-{{.OS}}-{{.Arch}}/{{.Dir}}"
  .
before_deploy:
- ls -l dist
- rm ${TRAVIS_BUILD_DIR}/glide.lock
deploy:
  provider: s3
  access_key_id: AKIAIAFSJLCCOYB5V3EQ
  secret_access_key:
    secure: e/EvHbTxLx7uoRIoHTJ9QrhTvzH8JelwyoRj+MY0elLzj+6ZkOsgDqbDaborrRg/EecD9kwAbSEzFk6fPNjpnWKcoL5/PJ02sGiP5zwS+N0QuGcfyei6Xs81uIDVXQCf9XQ4Unrhalfpv2ktskScvEKkruutPo8FzFqH3+XSxmYCsDEYGj/HjZtXV7Rn+5wPyGAFXB9KjZNdcBVsOdew1QCtcF7AMwg+ufkYAzbeEGo5S3FIk7wh9FpWV/7StB0LTcymlwpHJUBXcxC+i0kwXe37wmTZSa+8gcu506MDzPHfavyZWh+Ta9K/Y9hIh6wF+2p+RWmIgKJJ4tEqo9oxiiczJvE+3WjwB3psfLBh0/SmqMtfKoh72CbSBGdwQ0j2XkHUxTYYyVJ4q0jWI7gLkp0QShkwd9STPcAmytxb8hpEH2Zox8BoMYsR7F7J4A+8Va5eEPVielsmeA5OJzobI89XNM3kQkEJ/tgqlf3gzkoEePLdqhJx6NKxw9FE5gXOYBS0l9hbPnyYbLksUpXTAgZJc2MWpFjM1t1h+IFhQATo+EeMPM4SX0XmgcyeS/zKuyQ6dQ4WB2of4joIbAJv7o40nYSNVhYLuCIo8uEv4BaxWWVCnLWFQUm1UKU9W5dGMK6BTjvNvZQ03F9Fl4ySOSnoTrlcs3wOYf3COK1+BXw=
  bucket: files.rai-project.com
  local-dir: dist
  upload-dir: dist
  acl: public_read
  skip_cleanup: true
  detect_encoding: true
  on:
    repo: rai-project/rai-srcmanager
