language: go
go:
- '1.8.x'
dist: trusty
sudo: false
addons:
  apt:
    sources:
    - sourceline: ppa:masterminds/glide
    packages:
    - glide

before_install:
  - go get -u github.com/golang/dep/cmd/dep
  - |
    V=0.9.0
    OS=linux
    wget -nv -O install.sh "https://github.com/bazelbuild/bazel/releases/download/${V}/bazel-${V}-installer-${OS}-x86_64.sh"
    chmod +x install.sh
    ./install.sh --user
    rm -f install.sh
    mv .bazelrc.travis .bazelrc
script:
  - make dep 
  - make 
after_script:
- pwd
- ls -l
# - cd ${TRAVIS_BUILD_DIR}/cmd && go generate && cd ${TRAVIS_BUILD_DIR}
# - cd ${TRAVIS_BUILD_DIR}/pkg && go generate && cd ${TRAVIS_BUILD_DIR}
# - DIST=${TRAVIS_BUILD_DIR}/dist/rai-srcmanager/stable
# - CGO_ENABLED=0 gox -verbose -ldflags="$(govvv -flags)" -ldflags="-s -w" -os="linux
#   darwin windows" -arch="amd64 386 armv5 armv6 armv7 arm64" -osarch="!darwin/arm64
#   linux/ppc64 linux/ppc64le"
#   -ldflags "-extldflags \"-static\"" -output="${DIST}/${VERSION}/{{.OS}}-{{.Arch}}/{{.Dir}}"
#   .
