language: go
go:
  - '1.7'
sudo: true
before_install:
  - sudo add-apt-repository ppa:masterminds/glide -y
  - sudo apt-get update -q
  - sudo apt-get install glide -y
install:
  - glide install
  - go get github.com/GeertJohan/go.rice/rice
  - cd pkg && rice embed-go
script:
  - go test -v $(glide novendor)
