language: go
go:
- '1.8'
sudo: true
before_install:
- sudo add-apt-repository ppa:masterminds/glide -y
- sudo apt-get update -q
- sudo apt-get install glide -y
install:
- glide install
- go get github.com/mjibson/esc
- go get github.com/ahmetb/govvv
- go get github.com/franciscocpg/gox
- go get github.com/sanbornm/go-selfupdate
script:
- pwd
- ls -l
- cd ${TRAVIS_BUILD_DIR}/cmd && go generate && cd ${TRAVIS_BUILD_DIR}
- cd ${TRAVIS_BUILD_DIR}/pkg && go generate && cd ${TRAVIS_BUILD_DIR}
- DIST=${TRAVIS_BUILD_DIR}/dist/rai-srcmanager/stable
- CGO_ENABLED=0 gox -verbose -ldflags="$(govvv -flags)" -ldflags="-s -w" -os="linux
  darwin windows" -arch="amd64 386 armv5 armv6 armv7 arm64" -osarch="!darwin/arm64
  linux/ppc64 linux/ppc64le"
  -ldflags "-extldflags \"-static\"" -output="${DIST}/${VERSION}/{{.OS}}-{{.Arch}}/{{.Dir}}"
  .
before_deploy:
- echo "go-selfupdate generating bindiffs"
- mkdir -p ${DIST}/${VERSION}/binaries
- mkdir -p ${DIST}/latest
- tar --transform 's/.*\///g' -czvf ${DIST}/${VERSION}/binaries/darwin-386     ${DIST}/${VERSION}/darwin-386/rai-srcmanager        ${TRAVIS_BUILD_DIR}/LICENSE.TXT
  ${TRAVIS_BUILD_DIR}/VERSION
- tar --transform 's/.*\///g' -czvf ${DIST}/${VERSION}/binaries/darwin-amd64   ${DIST}/${VERSION}/darwin-amd64/rai-srcmanager      ${TRAVIS_BUILD_DIR}/LICENSE.TXT
  ${TRAVIS_BUILD_DIR}/VERSION
- tar --transform 's/.*\///g' -czvf ${DIST}/${VERSION}/binaries/linux-386      ${DIST}/${VERSION}/linux-386/rai-srcmanager         ${TRAVIS_BUILD_DIR}/LICENSE.TXT
  ${TRAVIS_BUILD_DIR}/VERSION
- tar --transform 's/.*\///g' -czvf ${DIST}/${VERSION}/binaries/linux-amd64    ${DIST}/${VERSION}/linux-amd64/rai-srcmanager       ${TRAVIS_BUILD_DIR}/LICENSE.TXT
  ${TRAVIS_BUILD_DIR}/VERSION
- tar --transform 's/.*\///g' -czvf ${DIST}/${VERSION}/binaries/linux-armv5    ${DIST}/${VERSION}/linux-armv5/rai-srcmanager       ${TRAVIS_BUILD_DIR}/LICENSE.TXT
  ${TRAVIS_BUILD_DIR}/VERSION
- tar --transform 's/.*\///g' -czvf ${DIST}/${VERSION}/binaries/linux-armv6    ${DIST}/${VERSION}/linux-armv6/rai-srcmanager       ${TRAVIS_BUILD_DIR}/LICENSE.TXT
  ${TRAVIS_BUILD_DIR}/VERSION
- tar --transform 's/.*\///g' -czvf ${DIST}/${VERSION}/binaries/linux-armv7    ${DIST}/${VERSION}/linux-armv7/rai-srcmanager       ${TRAVIS_BUILD_DIR}/LICENSE.TXT
  ${TRAVIS_BUILD_DIR}/VERSION
- tar --transform 's/.*\///g' -czvf ${DIST}/${VERSION}/binaries/linux-arm64    ${DIST}/${VERSION}/linux-arm64/rai-srcmanager       ${TRAVIS_BUILD_DIR}/LICENSE.TXT
  ${TRAVIS_BUILD_DIR}/VERSION
- tar --transform 's/.*\///g' -czvf ${DIST}/${VERSION}/binaries/linux-ppc64    ${DIST}/${VERSION}/linux-ppc64/rai-srcmanager       ${TRAVIS_BUILD_DIR}/LICENSE.TXT
  ${TRAVIS_BUILD_DIR}/VERSION
- tar --transform 's/.*\///g' -czvf ${DIST}/${VERSION}/binaries/linux-ppc64le  ${DIST}/${VERSION}/linux-ppc64le/rai-srcmanager     ${TRAVIS_BUILD_DIR}/LICENSE.TXT
  ${TRAVIS_BUILD_DIR}/VERSION
- tar --transform 's/.*\///g' -czvf ${DIST}/${VERSION}/binaries/windows-386    ${DIST}/${VERSION}/windows-386/rai-srcmanager.exe   ${TRAVIS_BUILD_DIR}/LICENSE.TXT
  ${TRAVIS_BUILD_DIR}/VERSION
- tar --transform 's/.*\///g' -czvf ${DIST}/${VERSION}/binaries/windows-amd64  ${DIST}/${VERSION}/windows-amd64/rai-srcmanager.exe
  ${TRAVIS_BUILD_DIR}/LICENSE.TXT ${TRAVIS_BUILD_DIR}/VERSION
- go-selfupdate -o ${DIST}/updates ${DIST}/${VERSION}/binaries/ ${VERSION}
- cp ${DIST}/${VERSION}/binaries/darwin-386    ${DIST}/latest/darwin-386.tar.gz
- cp ${DIST}/${VERSION}/binaries/darwin-amd64  ${DIST}/latest/darwin-amd64.tar.gz
- cp ${DIST}/${VERSION}/binaries/linux-386     ${DIST}/latest/linux-386.tar.gz
- cp ${DIST}/${VERSION}/binaries/linux-amd64   ${DIST}/latest/linux-amd64.tar.gz
- cp ${DIST}/${VERSION}/binaries/linux-armv5   ${DIST}/latest/linux-armv5.tar.gz
- cp ${DIST}/${VERSION}/binaries/linux-armv6   ${DIST}/latest/linux-armv6.tar.gz
- cp ${DIST}/${VERSION}/binaries/linux-armv7   ${DIST}/latest/linux-armv7.tar.gz
- cp ${DIST}/${VERSION}/binaries/linux-arm64   ${DIST}/latest/linux-arm64.tar.gz
- cp ${DIST}/${VERSION}/binaries/linux-ppc64   ${DIST}/latest/linux-ppc64.tar.gz
- cp ${DIST}/${VERSION}/binaries/linux-ppc64le ${DIST}/latest/linux-ppc64le.tar.gz
- cp ${DIST}/${VERSION}/binaries/windows-386   ${DIST}/latest/windows-386.tar.gz
- cp ${DIST}/${VERSION}/binaries/windows-amd64 ${DIST}/latest/windows-amd64.tar.gz
- rm -fr ${DIST}/${VERSION}/binaries
- echo "Copying latest directory to ${DIST}/${TRAVIS_COMMIT}"
- cp -r ${DIST}/latest ${DIST}/${TRAVIS_COMMIT}
after_deploy:
- echo "releasing v${VERSION}..."
- ghr -t "$GITHUB_TOKEN" -u rai-project -r rai --replace "v${VERSION}" "${DIST}/latest"
- cd ${TRAVIS_BUILD_DIR}
deploy:
  provider: s3
  access_key_id: AKIAIAFSJLCCOYB5V3EQ
  secret_access_key:
    secure: e/EvHbTxLx7uoRIoHTJ9QrhTvzH8JelwyoRj+MY0elLzj+6ZkOsgDqbDaborrRg/EecD9kwAbSEzFk6fPNjpnWKcoL5/PJ02sGiP5zwS+N0QuGcfyei6Xs81uIDVXQCf9XQ4Unrhalfpv2ktskScvEKkruutPo8FzFqH3+XSxmYCsDEYGj/HjZtXV7Rn+5wPyGAFXB9KjZNdcBVsOdew1QCtcF7AMwg+ufkYAzbeEGo5S3FIk7wh9FpWV/7StB0LTcymlwpHJUBXcxC+i0kwXe37wmTZSa+8gcu506MDzPHfavyZWh+Ta9K/Y9hIh6wF+2p+RWmIgKJJ4tEqo9oxiiczJvE+3WjwB3psfLBh0/SmqMtfKoh72CbSBGdwQ0j2XkHUxTYYyVJ4q0jWI7gLkp0QShkwd9STPcAmytxb8hpEH2Zox8BoMYsR7F7J4A+8Va5eEPVielsmeA5OJzobI89XNM3kQkEJ/tgqlf3gzkoEePLdqhJx6NKxw9FE5gXOYBS0l9hbPnyYbLksUpXTAgZJc2MWpFjM1t1h+IFhQATo+EeMPM4SX0XmgcyeS/zKuyQ6dQ4WB2of4joIbAJv7o40nYSNVhYLuCIo8uEv4BaxWWVCnLWFQUm1UKU9W5dGMK6BTjvNvZQ03F9Fl4ySOSnoTrlcs3wOYf3COK1+BXw=
  bucket: files.rai-project.com
  local-dir: dist
  upload-dir: dist
  acl: public_read
  skip_cleanup: true
  detect_encoding: true
  on:
    repo: rai-project/rai-srcmanager
