language: go
matrix:
  include:
    - go: 1.10.x
    - go: 1.11.x
    - go: tip
  allow_failures:
    - go: tip
dist: xenial
sudo: false
addons:
  apt:
    sources:
      - sourceline: ppa:masterminds/glide
    packages:
      - glide
install:
  - glide install --force
  - go build
script:
  - echo "Skip tests..."
after_script:
  - go test -race -v .
