// Code generated by "esc -o pkg/static_content.go -pkg srcmanager -private repositories"; DO NOT EDIT.

package srcmanager

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"io/ioutil"
	"net/http"
	"os"
	"path"
	"sync"
	"time"
)

type _escLocalFS struct{}

var _escLocal _escLocalFS

type _escStaticFS struct{}

var _escStatic _escStaticFS

type _escDirectory struct {
	fs   http.FileSystem
	name string
}

type _escFile struct {
	compressed string
	size       int64
	modtime    int64
	local      string
	isDir      bool

	once sync.Once
	data []byte
	name string
}

func (_escLocalFS) Open(name string) (http.File, error) {
	f, present := _escData[path.Clean(name)]
	if !present {
		return nil, os.ErrNotExist
	}
	return os.Open(f.local)
}

func (_escStaticFS) prepare(name string) (*_escFile, error) {
	f, present := _escData[path.Clean(name)]
	if !present {
		return nil, os.ErrNotExist
	}
	var err error
	f.once.Do(func() {
		f.name = path.Base(name)
		if f.size == 0 {
			return
		}
		var gr *gzip.Reader
		b64 := base64.NewDecoder(base64.StdEncoding, bytes.NewBufferString(f.compressed))
		gr, err = gzip.NewReader(b64)
		if err != nil {
			return
		}
		f.data, err = ioutil.ReadAll(gr)
	})
	if err != nil {
		return nil, err
	}
	return f, nil
}

func (fs _escStaticFS) Open(name string) (http.File, error) {
	f, err := fs.prepare(name)
	if err != nil {
		return nil, err
	}
	return f.File()
}

func (dir _escDirectory) Open(name string) (http.File, error) {
	return dir.fs.Open(dir.name + name)
}

func (f *_escFile) File() (http.File, error) {
	type httpFile struct {
		*bytes.Reader
		*_escFile
	}
	return &httpFile{
		Reader:   bytes.NewReader(f.data),
		_escFile: f,
	}, nil
}

func (f *_escFile) Close() error {
	return nil
}

func (f *_escFile) Readdir(count int) ([]os.FileInfo, error) {
	return nil, nil
}

func (f *_escFile) Stat() (os.FileInfo, error) {
	return f, nil
}

func (f *_escFile) Name() string {
	return f.name
}

func (f *_escFile) Size() int64 {
	return f.size
}

func (f *_escFile) Mode() os.FileMode {
	return 0
}

func (f *_escFile) ModTime() time.Time {
	return time.Unix(f.modtime, 0)
}

func (f *_escFile) IsDir() bool {
	return f.isDir
}

func (f *_escFile) Sys() interface{} {
	return f
}

// _escFS returns a http.Filesystem for the embedded assets. If useLocal is true,
// the filesystem's contents are instead used.
func _escFS(useLocal bool) http.FileSystem {
	if useLocal {
		return _escLocal
	}
	return _escStatic
}

// _escDir returns a http.Filesystem for the embedded assets on a given prefix dir.
// If useLocal is true, the filesystem's contents are instead used.
func _escDir(useLocal bool, name string) http.FileSystem {
	if useLocal {
		return _escDirectory{fs: _escLocal, name: name}
	}
	return _escDirectory{fs: _escStatic, name: name}
}

// _escFSByte returns the named file from the embedded assets. If useLocal is
// true, the filesystem's contents are instead used.
func _escFSByte(useLocal bool, name string) ([]byte, error) {
	if useLocal {
		f, err := _escLocal.Open(name)
		if err != nil {
			return nil, err
		}
		b, err := ioutil.ReadAll(f)
		_ = f.Close()
		return b, err
	}
	f, err := _escStatic.prepare(name)
	if err != nil {
		return nil, err
	}
	return f.data, nil
}

// _escFSMustByte is the same as _escFSByte, but panics if name is not present.
func _escFSMustByte(useLocal bool, name string) []byte {
	b, err := _escFSByte(useLocal, name)
	if err != nil {
		panic(err)
	}
	return b
}

// _escFSString is the string version of _escFSByte.
func _escFSString(useLocal bool, name string) (string, error) {
	b, err := _escFSByte(useLocal, name)
	return string(b), err
}

// _escFSMustString is the string version of _escFSMustByte.
func _escFSMustString(useLocal bool, name string) string {
	return string(_escFSMustByte(useLocal, name))
}

var _escData = map[string]*_escFile{

	"/repositories": {
		local:   "repositories",
		size:    4821,
		modtime: 1565992038,
		compressed: `
H4sIAAAAAAAC/7SXz67sJgzG9+cprtR1eqSzqdR136KqIgccxjMGI+NkZu7TV5npP6kyYXPXvy9AzOcP
SGSXbfk5SP5UoKmqXDHYJ2i40I4fHt7s4rJ789CickN16ZbrjtpIiicJsK7YhV8ezZwlIrcg1R+BCYu5
NEcXFbu5TMpKqUMNH/6copjZpXVzkVH2Sx22CFRW8XgEgwWaW6jIh6Kh+YJVIeNd9OZLGJ7+EqOE2xld
iXFaNuLoK3/7R9n8we6FBWKGAskfCTOQuxW4A29gHe8mmbr2/Zt/9QQdnx14q0YdzrRcK6aOIj+Kv6lJ
pgoxMn77vSrtYPhHV1p7azEsTVQ7kx2N49MohmX3uSTGwLK5PZv85klag8cuCOyHH2VI7g5TYZdxDBAu
Pqbl5v4sS7j5LHUsnSFcqLizZjSl0D5++uYJKKgsWIJbkFfo+rCQiVJxLdn1Y5GIMz6qqPm/WHaKBIOy
qWXyFZmn5EbmuzN8qsDsV6KirqIZSvCHoIrc2azKVNzFV5UjAl28LW1bPKpAHTS9s3jahbeMPeENnwlL
RxF9ZsiUyXwrKkKwKUiuUrCYG/aKiZrpszcSIzScTITdYVpQMN/2DYP6xm2oBEzffTs21L1PyXdKM9EO
VITs0mczzL1Aeef2ynLvK/xkN9Fw+eX8DDGF4NdgM/J3Z9t8L+1UUQ1S8wXfzxd3R7ddHtev5tcmKfgJ
c7SpR9eawDftHZfaOXqOC98MleZ+UYOfb1fMwCyhM0MpJ8Mft4Lna/vdIOpjKeXhR2xrTIt/EEJcgLsJ
ezw+mmGxAXO+TH5cz+fX+Tf6hdR2Lo18nAfzHZdGhqP6AR0cBjvX/XVazHeFOnbXey5U4rm0Pd3OgMB+
5fwHUpZwm6pipGDiPy2PrO5cM66Cq1KEp7/wYhc0CvPho4+LWW2/fn76FcFwAfVPofze4WOwhOW8cIfx
Z3xArowDBsKYcLa6nStfwXClAcczLTNLmitoQz3X//fBPUcJbY64D3gUsb6++QE2/fe6OiTfbStjbx1b
eahRR3Wv7U5Y5ncJh9ZwfKNbOd79Y8XAIgN1GJQdRdjzQAVGRMffVCw7FRmo1f+VfwYAAP//qRQd59US
AAA=
`,
	},

	"/": {
		isDir: true,
		local: "",
	},
}
