// Code generated by "esc -o pkg/static_content.go -pkg srcmanager -private repositories"; DO NOT EDIT.

package srcmanager

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"io/ioutil"
	"net/http"
	"os"
	"path"
	"sync"
	"time"
)

type _escLocalFS struct{}

var _escLocal _escLocalFS

type _escStaticFS struct{}

var _escStatic _escStaticFS

type _escDirectory struct {
	fs   http.FileSystem
	name string
}

type _escFile struct {
	compressed string
	size       int64
	modtime    int64
	local      string
	isDir      bool

	once sync.Once
	data []byte
	name string
}

func (_escLocalFS) Open(name string) (http.File, error) {
	f, present := _escData[path.Clean(name)]
	if !present {
		return nil, os.ErrNotExist
	}
	return os.Open(f.local)
}

func (_escStaticFS) prepare(name string) (*_escFile, error) {
	f, present := _escData[path.Clean(name)]
	if !present {
		return nil, os.ErrNotExist
	}
	var err error
	f.once.Do(func() {
		f.name = path.Base(name)
		if f.size == 0 {
			return
		}
		var gr *gzip.Reader
		b64 := base64.NewDecoder(base64.StdEncoding, bytes.NewBufferString(f.compressed))
		gr, err = gzip.NewReader(b64)
		if err != nil {
			return
		}
		f.data, err = ioutil.ReadAll(gr)
	})
	if err != nil {
		return nil, err
	}
	return f, nil
}

func (fs _escStaticFS) Open(name string) (http.File, error) {
	f, err := fs.prepare(name)
	if err != nil {
		return nil, err
	}
	return f.File()
}

func (dir _escDirectory) Open(name string) (http.File, error) {
	return dir.fs.Open(dir.name + name)
}

func (f *_escFile) File() (http.File, error) {
	type httpFile struct {
		*bytes.Reader
		*_escFile
	}
	return &httpFile{
		Reader:   bytes.NewReader(f.data),
		_escFile: f,
	}, nil
}

func (f *_escFile) Close() error {
	return nil
}

func (f *_escFile) Readdir(count int) ([]os.FileInfo, error) {
	return nil, nil
}

func (f *_escFile) Stat() (os.FileInfo, error) {
	return f, nil
}

func (f *_escFile) Name() string {
	return f.name
}

func (f *_escFile) Size() int64 {
	return f.size
}

func (f *_escFile) Mode() os.FileMode {
	return 0
}

func (f *_escFile) ModTime() time.Time {
	return time.Unix(f.modtime, 0)
}

func (f *_escFile) IsDir() bool {
	return f.isDir
}

func (f *_escFile) Sys() interface{} {
	return f
}

// _escFS returns a http.Filesystem for the embedded assets. If useLocal is true,
// the filesystem's contents are instead used.
func _escFS(useLocal bool) http.FileSystem {
	if useLocal {
		return _escLocal
	}
	return _escStatic
}

// _escDir returns a http.Filesystem for the embedded assets on a given prefix dir.
// If useLocal is true, the filesystem's contents are instead used.
func _escDir(useLocal bool, name string) http.FileSystem {
	if useLocal {
		return _escDirectory{fs: _escLocal, name: name}
	}
	return _escDirectory{fs: _escStatic, name: name}
}

// _escFSByte returns the named file from the embedded assets. If useLocal is
// true, the filesystem's contents are instead used.
func _escFSByte(useLocal bool, name string) ([]byte, error) {
	if useLocal {
		f, err := _escLocal.Open(name)
		if err != nil {
			return nil, err
		}
		b, err := ioutil.ReadAll(f)
		_ = f.Close()
		return b, err
	}
	f, err := _escStatic.prepare(name)
	if err != nil {
		return nil, err
	}
	return f.data, nil
}

// _escFSMustByte is the same as _escFSByte, but panics if name is not present.
func _escFSMustByte(useLocal bool, name string) []byte {
	b, err := _escFSByte(useLocal, name)
	if err != nil {
		panic(err)
	}
	return b
}

// _escFSString is the string version of _escFSByte.
func _escFSString(useLocal bool, name string) (string, error) {
	b, err := _escFSByte(useLocal, name)
	return string(b), err
}

// _escFSMustString is the string version of _escFSMustByte.
func _escFSMustString(useLocal bool, name string) string {
	return string(_escFSMustByte(useLocal, name))
}

var _escData = map[string]*_escFile{

	"/repositories": {
		local:   "repositories",
		size:    3765,
		modtime: 1542382440,
		compressed: `
H4sIAAAAAAAC/4yXQY7kNgxF932KAWbtDNCbXCC3CIICLdEqdlGiQNGurjl94Goku6/q9fumZOnzS/pZ
JK77+key+stJlu72wSl+hVPi3t8AJk9XORjiPa6Q3QdCq9uNHdK99oN9iDUkSbRtPIXviFatlllHso4r
qHALSGuGqMUNMmublAkN/sRjmnNVSPsOUUjFS532TNI2QzxT0EoDLlTWUzE4sGBzqnw3v2GJ0gNPMVu6
vaKbKC/rLpqx8q//lQMXuzc1ypUaFVyJKwncCj5Id4qJd4stU/v+x99ngonPTrz3kAlXWT86l4mifja8
qcWWTjkr//i7uxwU/M9U2mdzCW7D3CeDnY2DabbgdmBuRTmp7bBnC26e4j0hdmVSHH5SqcAdlqaQaU6U
rhjLeoM/q5ZumJWJpSulqzQ4auVwSbBvqiS3lVuCy/GMXAybhLk0aMipG5tlvvBnNw/8g+2QLPRN2TKq
YEXVpcDA/OoLTJ1U8Up09s28Uku4hHTWyVZ1lQYn393OAIR4X8e+IuokE7R8JfFymO6VZ8IbPwq3iSJj
FqxSJd5+/kASphRLstqtcQtoWeciI/wxq6RMg5cwU1hmJKfAth+cHBt3sAup/MZ2HOzHnAp2ygjzCXSm
CuljBNdZnHyl9qZ2nytwrod5uv75+gR5XlDhGuwheHf2HXvpkM4eVAYW/H49uTvDdvn8eMeBqQt5WiZf
BxcnnEFnIyO69ULY1nde++RoOi+EF+pymS97wgn4wZVULU1GaO1F+fPW8HgaBCmstU+csmOorPgkpLyS
TkP2fH2M4Bbf8OfT5+f9/PI8Ar/7hfXxWpr1PBIud16HBH9X/1o3HtCblBRPHD9QqqXb0p2zpDD8tDvT
cnLQj0eLK4eky7lLb/8GAAD//0A9Gk61DgAA
`,
	},

	"/": {
		isDir: true,
		local: "",
	},
}
